### ISSUE TITLE
Does not work on mac. 

### ISSUE THREAD

**Issue by seanrichardweber** [jacogrande/codactor-web#1]
I tried to install this on mac. And nothing. Made me worry that it was malware or something.

**Comment by ZMobile** [comment]
Apologies for that. I just realized the latest version on the site is entirely non functional. Dev work was moved primarily to focus on the Intellij plugin so I must've rushed an update.

I've just restored the website version to an older version for the meantime while I look into this. Let me know if the problem persists. I also created a new github repo with the stable/working version of the jar where you can also download it as a fallback: https://github.com/ZMobile/codactor-stable-jar

Thanks for reporting this.

**Comment by seanrichardweber** [comment]
i am very grateful for your quick response and excited to try this out. I will check back soon with any issues. :)

**Comment by seanrichardweber** [comment]
the problem persists. I tried on mac os and windows. both latest. both latest java.

**Comment by ZMobile** [comment]
I’m sorry to hear that. Is this issue occurring with the jar downloaded on the website or the one in the stable link above?

**Comment by seanrichardweber** [comment]
both. i am happy to check logs and provide whatever feedback you need.  java exception has occurred.

**Comment by seanrichardweber** [comment]
i also tried on a windows machine. same experience.

**Comment by ZMobile** [comment]
@seanrichardweber That would be great if you could provide logs. Again, sorry to hear that. With the stable jar I hate to pull the “works on my machine” situation here but it seems to be the case.

I’ll look over the logs and try to fix your specific issue either today or tomorrow/Tuesday.

**Comment by ZMobile** [comment]
@seanrichardweber but again if you could provide those logs of the Java exception that’d be extremely helpful then I’ll find what’s wrong with your specific case

**Comment by seanrichardweber** [comment]
= i think it might be an older versioner of java Runtime... updating my machine with the newer version. Will report back, 

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/translator/MainFrame has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:620)

**Comment by seanrichardweber** [comment]
@ZMobile - it appears that the updated runtime resolved the error. playing w the program now. thank you!

**Comment by ZMobile** [comment]
@seanrichardweber no problem! Glad to hear that updating Java on your machine resolved the issue, from the logs that definitely seemed to be the problem. 

Enjoy Codactor, and let me know if you have any feedback or further issues/bugs.
